In [1]:
import numpy as np
from landlab.components import PriorityFloodFlowRouter
from landlab.components.soil_grading import SoilGrading
from landlab import RasterModelGrid
import matplotlib.pyplot as plt

In [2]:
grid1 = RasterModelGrid((4, 5))
grid2 = RasterModelGrid((4, 5))
grid3 = RasterModelGrid((4, 5))

In [3]:
soil_density = 2650
phi=0.4
meansizes =[0.001, 0.01, 0.1]
grains__weight = np.zeros((np.size(grid1.nodes[:]),np.size(meansizes)))
grains__weight[grid1.core_nodes[0]][:]=100
grid1.at_node["grains__weight"] = grains__weight


In [4]:
# Try to init using pre-existing grains__weight field and given the field name
sg = SoilGrading(grid1,
                 meansizes=meansizes,
                 grains_weight='grains__weight',
                 phi=phi,
                 soil_density=soil_density)


creating MSW
creating GCS
creating BGP
creating SD
SG was given a preexisting GW


In [5]:
print(grid1.at_node['grains__weight'][grid1.core_nodes[0]])

[100. 100. 100.]


In [6]:
# Now lets try to init given the vector itself
grid2.at_node["grains__weight"] = grains__weight
sg = SoilGrading(grid2,
                 meansizes=meansizes,
                 grains_weight=grains__weight,
                 phi=phi,
                 soil_density=soil_density)

creating MSW
creating GCS
creating BGP
creating SD
SG was given a preexisting GW


In [7]:
print(grid2.at_node['grains__weight'][grid2.core_nodes[0]])

[100. 100. 100.]


In [8]:
# I can also think about a case in which we want to init based on existing field 
# that is not "grains__weight". Lets call this field "init_grains__weights".
grid3.at_node["init_grains__weights"] = grains__weight
sg = SoilGrading(grid3,
                 meansizes=meansizes,
                 grains_weight="init_grains__weights",
                 phi=phi,
                 soil_density=soil_density)


creating MSW
creating GCS
creating BGP
creating SD


In [9]:
print(grid3.at_node['grains__weight'][grid3.core_nodes[0]])

[100. 100. 100.]


In [10]:
# Try it with just a single grain-size fraction
grid4 = RasterModelGrid((4, 5))
grid5 = RasterModelGrid((4, 5))
grid6 = RasterModelGrid((4, 5))

In [11]:
soil_density = 2650
phi=0.4
meansizes1 =[0.01]
grains__weight = np.zeros((np.size(grid4.nodes[:]),np.size(meansizes)))
grains__weight[grid4.core_nodes[0]][:]=100
grid4.at_node["grains__weight"] = grains__weight

In [45]:
# Try to init with 1 size class using pre-existing grains__weight field and given the field name
sg = SoilGrading(grid4,
                 meansizes=meansizes1,
                 grains_weight='grains__weight',
                 phi=phi,
                 soil_density=soil_density)

creating MSW
creating GCS
creating BGP
creating SD
SG was given a preexisting GW


IndexError: tuple index out of range

In [46]:
print(grid4.at_node['grains__weight'][grid4.core_nodes[0]])

[100. 100. 100.]


In [ ]:
# Now lets try to init given the vector itself, WITH ONE SIZE CLASS
grid5.at_node["grains__weight"] = grains__weight
sg = SoilGrading(grid5,
                 meansizes=meansizes1,
                 grains_weight=grains__weight,
                 phi=phi,
                 soil_density=soil_density)

In [ ]:
print(grid5.at_node['grains__weight'][grid5.core_nodes[0]])

In [ ]:
# case in which we want to init based on existing field WITH ONE SIZE CLASS
# that is not "grains__weight". Lets call this field "init_grains__weights".
grid6.at_node["init_grains__weights"] = grains__weight
sg = SoilGrading(grid6,
                 meansizes=meansizes1,
                 grains_weight="init_grains__weights",
                 phi=phi,
                 soil_density=soil_density)


In [ ]:
print(grid6.at_node['grains__weight'][grid6.core_nodes[0]])