In [12]:
import numpy as np
from landlab.components import PriorityFloodFlowRouter
from landlab.components.soil_grading import SoilGrading
from landlab import RasterModelGrid
import matplotlib.pyplot as plt

In [13]:
grid1 = RasterModelGrid((4, 5))
grid2 = RasterModelGrid((4, 5))
grid3 = RasterModelGrid((4, 5))

In [14]:
soil_density = 2650
phi=0.4
meansizes =[0.001, 0.01, 0.1]
grains__weight = np.zeros((np.size(grid1.nodes[:]),np.size(meansizes)))
grains__weight[grid1.core_nodes[0]][:]=100
grid1.at_node["grains__weight"] = grains__weight


In [15]:
# Try to init using pre-existing grains__weight field and given the field name
sg = SoilGrading(grid1,
                 meansizes=meansizes,
                 grains_weight='grains__weight',
                 phi=phi,
                 soil_density=soil_density)


creating MSW
creating GCS
creating BGP
creating SD
SG was given a preexisting GW


In [16]:
print(grid1.at_node['grains__weight'][grid1.core_nodes[0]])

[100. 100. 100.]


In [17]:
# Now lets try to init given the vector itself
grid2.at_node["grains__weight"] = grains__weight
sg = SoilGrading(grid2,
                 meansizes=meansizes,
                 grains_weight=grains__weight,
                 phi=phi,
                 soil_density=soil_density)

creating MSW
creating GCS
creating BGP
creating SD
SG was given a preexisting GW


In [18]:
print(grid2.at_node['grains__weight'][grid2.core_nodes[0]])

[100. 100. 100.]


In [19]:
# I can also think about a case in which we want to init based on existing field 
# that is not "grains__weight". Lets call this field "init_grains__weights".

grid3.at_node["init_grains__weights"] = grains__weight
sg = SoilGrading(grid3,
                 meansizes=meansizes,
                 grains_weight="init_grains__weights",
                 phi=phi,
                 soil_density=soil_density)


creating MSW
creating GCS
creating BGP
creating SD


In [20]:
print(grid3.at_node['grains__weight'][grid3.core_nodes[0]])

[100. 100. 100.]
